# fly.toml file generated for chi on 2021-10-28T16:45:04+08:00

app = "chi"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
APP_BIND_ADDR = "0.0.0.0:8080"
APP_CORPUS_URL = "https://raw.githubusercontent.com/Chi-Task-Force/Chi-Corpus/master/"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "get"
path = "/health-check"
protocol = "http"
timeout = 2000
tls_skip_verify = false